/*
 * This file is generated by jOOQ.
 */
package com.novafutur.financial.configuration.db;


import com.novafutur.financial.configuration.db.tables.LoanPlan;
import com.novafutur.financial.configuration.db.tables.User;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>nf_configuration</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LOAN_PLAN_PRIMARY = Indexes0.LOAN_PLAN_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LOAN_PLAN_PRIMARY = Internal.createIndex("PRIMARY", LoanPlan.LOAN_PLAN, new OrderField[] { LoanPlan.LOAN_PLAN.ID_LOAN_PLAN }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID_USER }, true);
    }
}
