/*
 * This file is generated by jOOQ.
 */
package com.novafutur.financial.configuration.db.tables.records;


import com.novafutur.financial.configuration.db.tables.LoanPlan;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanPlanRecord extends UpdatableRecordImpl<LoanPlanRecord> implements Record10<Integer, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, BigDecimal, Long, Integer> {

    private static final long serialVersionUID = -277852120;

    /**
     * Setter for <code>nf_configuration.loan_plan.id_loan_plan</code>.
     */
    public void setIdLoanPlan(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.id_loan_plan</code>.
     */
    public Integer getIdLoanPlan() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.date_create</code>.
     */
    public void setDateCreate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.date_create</code>.
     */
    public LocalDateTime getDateCreate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.date_update</code>.
     */
    public void setDateUpdate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.date_update</code>.
     */
    public LocalDateTime getDateUpdate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.date_delete</code>.
     */
    public void setDateDelete(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.date_delete</code>.
     */
    public LocalDateTime getDateDelete() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.parts</code>.
     */
    public void setParts(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.parts</code>.
     */
    public Integer getParts() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.interests</code>.
     */
    public void setInterests(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.interests</code>.
     */
    public BigDecimal getInterests() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.part_amount</code>.
     */
    public void setPartAmount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.part_amount</code>.
     */
    public Long getPartAmount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>nf_configuration.loan_plan.status</code>.
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>nf_configuration.loan_plan.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, BigDecimal, Long, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, BigDecimal, Long, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LoanPlan.LOAN_PLAN.ID_LOAN_PLAN;
    }

    @Override
    public Field<Integer> field2() {
        return LoanPlan.LOAN_PLAN.ID_USER;
    }

    @Override
    public Field<String> field3() {
        return LoanPlan.LOAN_PLAN.NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return LoanPlan.LOAN_PLAN.DATE_CREATE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return LoanPlan.LOAN_PLAN.DATE_UPDATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return LoanPlan.LOAN_PLAN.DATE_DELETE;
    }

    @Override
    public Field<Integer> field7() {
        return LoanPlan.LOAN_PLAN.PARTS;
    }

    @Override
    public Field<BigDecimal> field8() {
        return LoanPlan.LOAN_PLAN.INTERESTS;
    }

    @Override
    public Field<Long> field9() {
        return LoanPlan.LOAN_PLAN.PART_AMOUNT;
    }

    @Override
    public Field<Integer> field10() {
        return LoanPlan.LOAN_PLAN.STATUS;
    }

    @Override
    public Integer component1() {
        return getIdLoanPlan();
    }

    @Override
    public Integer component2() {
        return getIdUser();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDateTime component4() {
        return getDateCreate();
    }

    @Override
    public LocalDateTime component5() {
        return getDateUpdate();
    }

    @Override
    public LocalDateTime component6() {
        return getDateDelete();
    }

    @Override
    public Integer component7() {
        return getParts();
    }

    @Override
    public BigDecimal component8() {
        return getInterests();
    }

    @Override
    public Long component9() {
        return getPartAmount();
    }

    @Override
    public Integer component10() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getIdLoanPlan();
    }

    @Override
    public Integer value2() {
        return getIdUser();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDateTime value4() {
        return getDateCreate();
    }

    @Override
    public LocalDateTime value5() {
        return getDateUpdate();
    }

    @Override
    public LocalDateTime value6() {
        return getDateDelete();
    }

    @Override
    public Integer value7() {
        return getParts();
    }

    @Override
    public BigDecimal value8() {
        return getInterests();
    }

    @Override
    public Long value9() {
        return getPartAmount();
    }

    @Override
    public Integer value10() {
        return getStatus();
    }

    @Override
    public LoanPlanRecord value1(Integer value) {
        setIdLoanPlan(value);
        return this;
    }

    @Override
    public LoanPlanRecord value2(Integer value) {
        setIdUser(value);
        return this;
    }

    @Override
    public LoanPlanRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public LoanPlanRecord value4(LocalDateTime value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public LoanPlanRecord value5(LocalDateTime value) {
        setDateUpdate(value);
        return this;
    }

    @Override
    public LoanPlanRecord value6(LocalDateTime value) {
        setDateDelete(value);
        return this;
    }

    @Override
    public LoanPlanRecord value7(Integer value) {
        setParts(value);
        return this;
    }

    @Override
    public LoanPlanRecord value8(BigDecimal value) {
        setInterests(value);
        return this;
    }

    @Override
    public LoanPlanRecord value9(Long value) {
        setPartAmount(value);
        return this;
    }

    @Override
    public LoanPlanRecord value10(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public LoanPlanRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6, Integer value7, BigDecimal value8, Long value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanPlanRecord
     */
    public LoanPlanRecord() {
        super(LoanPlan.LOAN_PLAN);
    }

    /**
     * Create a detached, initialised LoanPlanRecord
     */
    public LoanPlanRecord(Integer idLoanPlan, Integer idUser, String name, LocalDateTime dateCreate, LocalDateTime dateUpdate, LocalDateTime dateDelete, Integer parts, BigDecimal interests, Long partAmount, Integer status) {
        super(LoanPlan.LOAN_PLAN);

        set(0, idLoanPlan);
        set(1, idUser);
        set(2, name);
        set(3, dateCreate);
        set(4, dateUpdate);
        set(5, dateDelete);
        set(6, parts);
        set(7, interests);
        set(8, partAmount);
        set(9, status);
    }
}
