/*
 * This file is generated by jOOQ.
 */
package com.novafutur.financial.configuration.db.tables.records;


import com.novafutur.financial.configuration.db.tables.User;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record14<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, String, String> {

    private static final long serialVersionUID = 374501776;

    /**
     * Setter for <code>nf_configuration.user.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nf_configuration.user.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nf_configuration.user.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nf_configuration.user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nf_configuration.user.surname</code>.
     */
    public void setSurname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nf_configuration.user.surname</code>.
     */
    public String getSurname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nf_configuration.user.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nf_configuration.user.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nf_configuration.user.date_birth</code>.
     */
    public void setDateBirth(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>nf_configuration.user.date_birth</code>.
     */
    public LocalDateTime getDateBirth() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>nf_configuration.user.date_create</code>.
     */
    public void setDateCreate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>nf_configuration.user.date_create</code>.
     */
    public LocalDateTime getDateCreate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>nf_configuration.user.date_update</code>.
     */
    public void setDateUpdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>nf_configuration.user.date_update</code>.
     */
    public LocalDateTime getDateUpdate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>nf_configuration.user.date_delete</code>.
     */
    public void setDateDelete(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>nf_configuration.user.date_delete</code>.
     */
    public LocalDateTime getDateDelete() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>nf_configuration.user.gov_id</code>.
     */
    public void setGovId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>nf_configuration.user.gov_id</code>.
     */
    public String getGovId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nf_configuration.user.username</code>.
     */
    public void setUsername(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>nf_configuration.user.username</code>.
     */
    public String getUsername() {
        return (String) get(9);
    }

    /**
     * Setter for <code>nf_configuration.user.password</code>.
     */
    public void setPassword(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>nf_configuration.user.password</code>.
     */
    public String getPassword() {
        return (String) get(10);
    }

    /**
     * Setter for <code>nf_configuration.user.email</code>.
     */
    public void setEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>nf_configuration.user.email</code>.
     */
    public String getEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>nf_configuration.user.gender</code>.
     */
    public void setGender(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>nf_configuration.user.gender</code>.
     */
    public String getGender() {
        return (String) get(12);
    }

    /**
     * Setter for <code>nf_configuration.user.status</code>.
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>nf_configuration.user.status</code>.
     */
    public String getStatus() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID_USER;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.SURNAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.TITLE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return User.USER.DATE_BIRTH;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return User.USER.DATE_CREATE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return User.USER.DATE_UPDATE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return User.USER.DATE_DELETE;
    }

    @Override
    public Field<String> field9() {
        return User.USER.GOV_ID;
    }

    @Override
    public Field<String> field10() {
        return User.USER.USERNAME;
    }

    @Override
    public Field<String> field11() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field12() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field13() {
        return User.USER.GENDER;
    }

    @Override
    public Field<String> field14() {
        return User.USER.STATUS;
    }

    @Override
    public Integer component1() {
        return getIdUser();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSurname();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public LocalDateTime component5() {
        return getDateBirth();
    }

    @Override
    public LocalDateTime component6() {
        return getDateCreate();
    }

    @Override
    public LocalDateTime component7() {
        return getDateUpdate();
    }

    @Override
    public LocalDateTime component8() {
        return getDateDelete();
    }

    @Override
    public String component9() {
        return getGovId();
    }

    @Override
    public String component10() {
        return getUsername();
    }

    @Override
    public String component11() {
        return getPassword();
    }

    @Override
    public String component12() {
        return getEmail();
    }

    @Override
    public String component13() {
        return getGender();
    }

    @Override
    public String component14() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getIdUser();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSurname();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public LocalDateTime value5() {
        return getDateBirth();
    }

    @Override
    public LocalDateTime value6() {
        return getDateCreate();
    }

    @Override
    public LocalDateTime value7() {
        return getDateUpdate();
    }

    @Override
    public LocalDateTime value8() {
        return getDateDelete();
    }

    @Override
    public String value9() {
        return getGovId();
    }

    @Override
    public String value10() {
        return getUsername();
    }

    @Override
    public String value11() {
        return getPassword();
    }

    @Override
    public String value12() {
        return getEmail();
    }

    @Override
    public String value13() {
        return getGender();
    }

    @Override
    public String value14() {
        return getStatus();
    }

    @Override
    public UserRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public UserRecord value5(LocalDateTime value) {
        setDateBirth(value);
        return this;
    }

    @Override
    public UserRecord value6(LocalDateTime value) {
        setDateCreate(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDateTime value) {
        setDateUpdate(value);
        return this;
    }

    @Override
    public UserRecord value8(LocalDateTime value) {
        setDateDelete(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setGovId(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value11(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value12(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value13(String value) {
        setGender(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer idUser, String name, String surname, String title, LocalDateTime dateBirth, LocalDateTime dateCreate, LocalDateTime dateUpdate, LocalDateTime dateDelete, String govId, String username, String password, String email, String gender, String status) {
        super(User.USER);

        set(0, idUser);
        set(1, name);
        set(2, surname);
        set(3, title);
        set(4, dateBirth);
        set(5, dateCreate);
        set(6, dateUpdate);
        set(7, dateDelete);
        set(8, govId);
        set(9, username);
        set(10, password);
        set(11, email);
        set(12, gender);
        set(13, status);
    }
}
