/*
 * This file is generated by jOOQ.
 */
package com.novafutur.financial.configuration.db.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanPlan implements Serializable {

    private static final long serialVersionUID = -1788101891;

    private Integer       idLoanPlan;
    private Integer       idUser;
    private String        name;
    private LocalDateTime dateCreate;
    private LocalDateTime dateUpdate;
    private LocalDateTime dateDelete;
    private Integer       parts;
    private BigDecimal    interests;
    private Long          partAmount;
    private Integer       status;

    public LoanPlan() {}

    public LoanPlan(LoanPlan value) {
        this.idLoanPlan = value.idLoanPlan;
        this.idUser = value.idUser;
        this.name = value.name;
        this.dateCreate = value.dateCreate;
        this.dateUpdate = value.dateUpdate;
        this.dateDelete = value.dateDelete;
        this.parts = value.parts;
        this.interests = value.interests;
        this.partAmount = value.partAmount;
        this.status = value.status;
    }

    public LoanPlan(
        Integer       idLoanPlan,
        Integer       idUser,
        String        name,
        LocalDateTime dateCreate,
        LocalDateTime dateUpdate,
        LocalDateTime dateDelete,
        Integer       parts,
        BigDecimal    interests,
        Long          partAmount,
        Integer       status
    ) {
        this.idLoanPlan = idLoanPlan;
        this.idUser = idUser;
        this.name = name;
        this.dateCreate = dateCreate;
        this.dateUpdate = dateUpdate;
        this.dateDelete = dateDelete;
        this.parts = parts;
        this.interests = interests;
        this.partAmount = partAmount;
        this.status = status;
    }

    public Integer getIdLoanPlan() {
        return this.idLoanPlan;
    }

    public void setIdLoanPlan(Integer idLoanPlan) {
        this.idLoanPlan = idLoanPlan;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDateTime getDateCreate() {
        return this.dateCreate;
    }

    public void setDateCreate(LocalDateTime dateCreate) {
        this.dateCreate = dateCreate;
    }

    public LocalDateTime getDateUpdate() {
        return this.dateUpdate;
    }

    public void setDateUpdate(LocalDateTime dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    public LocalDateTime getDateDelete() {
        return this.dateDelete;
    }

    public void setDateDelete(LocalDateTime dateDelete) {
        this.dateDelete = dateDelete;
    }

    public Integer getParts() {
        return this.parts;
    }

    public void setParts(Integer parts) {
        this.parts = parts;
    }

    public BigDecimal getInterests() {
        return this.interests;
    }

    public void setInterests(BigDecimal interests) {
        this.interests = interests;
    }

    public Long getPartAmount() {
        return this.partAmount;
    }

    public void setPartAmount(Long partAmount) {
        this.partAmount = partAmount;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoanPlan (");

        sb.append(idLoanPlan);
        sb.append(", ").append(idUser);
        sb.append(", ").append(name);
        sb.append(", ").append(dateCreate);
        sb.append(", ").append(dateUpdate);
        sb.append(", ").append(dateDelete);
        sb.append(", ").append(parts);
        sb.append(", ").append(interests);
        sb.append(", ").append(partAmount);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
