/*
 * This file is generated by jOOQ.
 */
package com.novafutur.financial.configuration.db.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1409450997;

    private Integer       idUser;
    private String        name;
    private String        surname;
    private String        title;
    private LocalDateTime dateBirth;
    private LocalDateTime dateCreate;
    private LocalDateTime dateUpdate;
    private LocalDateTime dateDelete;
    private String        govId;
    private String        username;
    private String        password;
    private String        email;
    private String        gender;
    private String        status;

    public User() {}

    public User(User value) {
        this.idUser = value.idUser;
        this.name = value.name;
        this.surname = value.surname;
        this.title = value.title;
        this.dateBirth = value.dateBirth;
        this.dateCreate = value.dateCreate;
        this.dateUpdate = value.dateUpdate;
        this.dateDelete = value.dateDelete;
        this.govId = value.govId;
        this.username = value.username;
        this.password = value.password;
        this.email = value.email;
        this.gender = value.gender;
        this.status = value.status;
    }

    public User(
        Integer       idUser,
        String        name,
        String        surname,
        String        title,
        LocalDateTime dateBirth,
        LocalDateTime dateCreate,
        LocalDateTime dateUpdate,
        LocalDateTime dateDelete,
        String        govId,
        String        username,
        String        password,
        String        email,
        String        gender,
        String        status
    ) {
        this.idUser = idUser;
        this.name = name;
        this.surname = surname;
        this.title = title;
        this.dateBirth = dateBirth;
        this.dateCreate = dateCreate;
        this.dateUpdate = dateUpdate;
        this.dateDelete = dateDelete;
        this.govId = govId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.gender = gender;
        this.status = status;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDateTime getDateBirth() {
        return this.dateBirth;
    }

    public void setDateBirth(LocalDateTime dateBirth) {
        this.dateBirth = dateBirth;
    }

    public LocalDateTime getDateCreate() {
        return this.dateCreate;
    }

    public void setDateCreate(LocalDateTime dateCreate) {
        this.dateCreate = dateCreate;
    }

    public LocalDateTime getDateUpdate() {
        return this.dateUpdate;
    }

    public void setDateUpdate(LocalDateTime dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    public LocalDateTime getDateDelete() {
        return this.dateDelete;
    }

    public void setDateDelete(LocalDateTime dateDelete) {
        this.dateDelete = dateDelete;
    }

    public String getGovId() {
        return this.govId;
    }

    public void setGovId(String govId) {
        this.govId = govId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(idUser);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(title);
        sb.append(", ").append(dateBirth);
        sb.append(", ").append(dateCreate);
        sb.append(", ").append(dateUpdate);
        sb.append(", ").append(dateDelete);
        sb.append(", ").append(govId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(gender);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
